[tool.poetry]
name = "mock_server"
version = "0.1.0"
description = ""
authors = ["Kalle Luopaj√§rvi <kalle.luopajarvi@helsinki.fi>"]

[tool.poetry.dependencies]
python = "^3.6"
connexion = "^2.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
